"""Initial migration for Decision Pack models.

Creates tables:
- decision_packs
- documents
- document_pages
- options
- evidence
- conflicts
"""

from alembic import op
import sqlalchemy as sa
import uuid

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def generate_uuid():
    return str(uuid.uuid4())

def upgrade():
    # ### commands auto generated by Alembic - please adjust as needed ###
    op.create_table(
        "decision_packs",
        sa.Column("id", sa.String(length=36), primary_key=True, default=generate_uuid),
        sa.Column("name", sa.String(length=255), nullable=False, server_default="Decision Pack"),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("policy_hurdle", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), onupdate=sa.func.now(), nullable=True),
        sa.Column("blocked", sa.Boolean(), nullable=False, server_default=sa.text("1")),
        sa.Column("block_reasons", sa.Text(), nullable=True),
    )

    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), primary_key=True, default=generate_uuid),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False, unique=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("admissible", sa.Boolean(), nullable=False, server_default=sa.text("1")),
        sa.Column("decision_pack_id", sa.String(length=36), sa.ForeignKey("decision_packs.id"), nullable=False),
    )

    op.create_table(
        "document_pages",
        sa.Column("id", sa.String(length=36), primary_key=True, default=generate_uuid),
        sa.Column("document_id", sa.String(length=36), sa.ForeignKey("documents.id"), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), onupdate=sa.func.now(), nullable=True),
    )

    op.create_table(
        "options",
        sa.Column("id", sa.String(length=36), primary_key=True, default=generate_uuid),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("decision_pack_id", sa.String(length=36), sa.ForeignKey("decision_packs.id"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), onupdate=sa.func.now(), nullable=True),
    )

    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=36), primary_key=True, default=generate_uuid),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Numeric(20, 6), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("option_id", sa.String(length=36), sa.ForeignKey("options.id"), nullable=True),
        sa.Column("source_document_id", sa.String(length=36), sa.ForeignKey("documents.id"), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("extract", sa.Text(), nullable=True),
        sa.Column("evidence_class", sa.Enum("MEASURED", "CLIENT_STATED", "ESTIMATE", name="evidenceclass"), nullable=False),
        sa.Column("status", sa.Enum("verified", "unverified_no_source", "conflict", "coverage_gap", "rejected", name="evidencestatus"), nullable=False),
        sa.Column("used_in_calculation", sa.Boolean(), nullable=False, server_default=sa.text("0")),
        sa.Column("owner", sa.String(length=255), nullable=True),
        sa.Column("as_of_date", sa.DateTime(), nullable=True),
        sa.Column("decision_pack_id", sa.String(length=36), sa.ForeignKey("decision_packs.id"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), onupdate=sa.func.now(), nullable=True),
    )

    op.create_table(
        "conflicts",
        sa.Column("id", sa.String(length=36), primary_key=True, default=generate_uuid),
        sa.Column("evidence_a_id", sa.String(length=36), sa.ForeignKey("evidence.id"), nullable=False),
        sa.Column("evidence_b_id", sa.String(length=36), sa.ForeignKey("evidence.id"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.Enum("unresolved", "resolved", name="conflictstatus"), nullable=False, server_default="unresolved"),
        sa.Column("selected_evidence_id", sa.String(length=36), sa.ForeignKey("evidence.id"), nullable=True),
        sa.Column("resolved_by", sa.String(length=255), nullable=True),
        sa.Column("resolution_basis", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), onupdate=sa.func.now(), nullable=True),
    )
    # ### end Alembic commands ###

def downgrade():
    op.drop_table("conflicts")
    op.drop_table("evidence")
    op.drop_table("options")
    op.drop_table("document_pages")
    op.drop_table("documents")
    op.drop_table("decision_packs")
