"""Update CalculationRun fields

Revision ID: 67508a58143e
Revises: fabad748b1ed
Create Date: 2026-10-04 03:21:10.843284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67508a58143e'
down_revision: Union[str, Sequence[str], None] = 'fabad748b1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculation_runs', sa.Column('inputs', sa.JSON(), nullable=True))
    op.add_column('calculation_runs', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('calculation_runs', sa.Column('reason', sa.String(length=255), nullable=True))
    op.add_column('calculation_runs', sa.Column('missing_evidence', sa.JSON(), nullable=True))
    op.alter_column('calculation_runs', 'value',
               existing_type=mysql.DECIMAL(precision=20, scale=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calculation_runs', 'value',
               existing_type=mysql.DECIMAL(precision=20, scale=6),
               nullable=False)
    op.drop_column('calculation_runs', 'missing_evidence')
    op.drop_column('calculation_runs', 'reason')
    op.drop_column('calculation_runs', 'status')
    op.drop_column('calculation_runs', 'inputs')
    # ### end Alembic commands ###
