"""Add status, content_type, file_path to Document

Revision ID: fabad748b1ed
Revises: 2e7c2bbf32c4
Create Date: 2026-10-04 02:31:25.161238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fabad748b1ed'
down_revision: Union[str, Sequence[str], None] = '2e7c2bbf32c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.String(length=512), nullable=False))
    op.add_column('documents', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('documents', 'admissible')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('admissible', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'content_type')
    # ### end Alembic commands ###
